spring.application.name=projetolab2


# configuracoes de conexao com banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/lab2
spring.datasource.username=postgres
spring.datasource.password=12345678

# configuracoes hibernate, gerenciador de conexoes com bancos SQL:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create