spring.application.name=projetolab2
# ==============================================================
# 1. CONFIGURAÇÕES DO SERVIDOR WEB
# ==============================================================
# Porta em que a aplicação vai rodar (8080 é o padrão)


# ==============================================================
# 2. CONFIGURAÇÕES DE CONEXÃO COM O MYSQL
# ==============================================================
# O banco será criado automaticamente como 'projetolab2' caso não exista
spring.datasource.url=jdbc:mysql://localhost:3306/projetolab2?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=will
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================================================
# 3. CONFIGURAÇÕES DO SPRING DATA JPA / HIBERNATE
# ==============================================================
# Atualiza as tabelas automaticamente de acordo com suas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Exibe o SQL gerado no console (ótimo para ver o que o Hibernate está fazendo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# 4. CONFIGURAÇÕES DE DATAS (JSON)
# ==============================================================
# Faz com que LocalDateTime, LocalDate e Instant apareçam no formato ISO-8601 (ex: "2024-10-25T15:30:00")
#spring.jackson.serialization.write-dates-as-timestamps=false

# ==============================================================
# 5. CONFIGURAÇÃO DA DOCUMENTAÇÃO SWAGGER (SPRINGDOC OPENAPI)
# ==============================================================
# Define a URL personalizada para acessar a interface visual do Swagger
springdoc.swagger-ui.path=/swagger-ui.html